backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Contact Information"
        name: "contact"
        file: "content/contact.json"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address Line 1", name: "address1", widget: "string"}
          - {label: "Address Line 2", name: "address2", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "State", name: "state", widget: "string"}
          - {label: "Zip", name: "zip", widget: "string"}

      - label: "Site Settings"
        name: "settings"
        file: "content/settings.json"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Description", name: "site_description", widget: "text"}
